"""
Draft agent: Generates article content with section markers.
"""

from api.graph.state import ContentState


def run_draft_agent(state: ContentState) -> dict:
    """
    Generate article draft with ##INTRO ##BODY ##CONCLUSION markers.

    Returns:
        dict: State updates with draft, incremented draft_version, cleared compliance_feedback
    """
    draft_content = """##INTRO
This is a stub introduction paragraph for testing purposes.

##BODY
This is the main body content. In production, this would be generated by the LLM based on the strategy and past feedback.

##CONCLUSION
This is a stub conclusion paragraph."""

    return {
        "draft": draft_content,
        "draft_version": state.get("draft_version", 0) + 1,
        "compliance_feedback": [],
        "pipeline_status": "draft_complete",
        "audit_log": state.get("audit_log", []) + [{"agent": "draft_agent", "action": "stub", "version": state.get("draft_version", 0) + 1}]
    }
